// Korean for every string the plugin shows; English is the key. Map text, what the server sends and what the AI reads are never translated.
// `tests/ko.test.ts` fails on a `t("…")` / `msg("…")` in the source with no entry here, and on an entry nothing uses.
export const KO: Record<string, string> = {
  " · you are in it": " · 참여 중",
  "(no description)": "(설명 없음)",
  "(picture)": "(그림)",
  "({credit} of it credit)": "(이 중 크레딧 {credit})",
  "A ceiling on one message with its tool rounds, and on one design or build. At the ceiling the work stops with the map as edited so far, the assistant offers to continue for as much again, and a build says which step it stopped at. 0 is no ceiling. A message usually costs $0.10–0.30 and a build $0.50–1.00; the server holds the ceiling, so the last call can run a little over it, never a whole extra one.": "도구 라운드를 포함한 메시지 하나, 그리고 설계나 빌드 하나에 거는 한도입니다. 한도에 닿으면 그때까지 편집한 맵 그대로 작업이 멈추고, 어시스턴트는 같은 금액만큼 더 계속할지 묻고, 빌드는 어느 단계에서 멈췄는지 알려 줍니다. 0이면 한도가 없습니다. 메시지 하나는 보통 $0.10–0.30, 빌드 하나는 $0.50–1.00이 듭니다. 한도는 서버가 지키므로 마지막 호출이 한도를 조금 넘을 수는 있지만 호출 하나가 통째로 더 붙지는 않습니다.",
  "A change could not be shared ({message}), so this copy no longer matches everyone else's. The map is still open here; save it, or join again.": "변경을 공유하지 못해 ({message}) 이 사본이 다른 사람들의 것과 더 이상 같지 않습니다. 맵은 여기에 그대로 열려 있으니 저장하거나 다시 참여하세요.",
  "A copy of the map: anyone can open their own": "맵 사본: 누구나 자기 사본을 열 수 있음",
  "A free trial of {amount} needs no sign-in.": "{amount} 무료 체험은 로그인이 필요 없습니다.",
  "A link opens a map kept on your scmjs.dev account, so making one takes an account. The people who open it need only the link.": "링크는 scmjs.dev 계정에 보관된 맵을 여는 것이라 링크를 만들려면 계정이 있어야 합니다. 링크를 여는 사람은 링크만 있으면 됩니다.",
  "A map is being shared already, or no map is open.": "이미 공유 중인 맵이 있거나 열린 맵이 없습니다.",
  "A map keeps its last revision; delete the map to remove it.": "맵에는 마지막 버전이 남아 있어야 합니다. 지우려면 맵을 삭제하세요.",
  "A new blank map of this size and tileset is made first, so the model can be told which terrains it has. An open map with unsaved changes asks before it goes.": "모델에게 어떤 지형이 있는지 알려 줄 수 있도록 이 크기와 타일셋의 빈 맵을 먼저 만듭니다. 저장하지 않은 변경이 있는 열린 맵은 닫기 전에 묻습니다.",
  "A new blank map of this size and tileset is made first. An open map with unsaved changes asks before it goes.": "이 크기와 타일셋의 빈 맵을 먼저 만듭니다. 저장하지 않은 변경이 있는 열린 맵은 닫기 전에 묻습니다.",
  "A new map": "새 맵",
  "A picture of the map that links to it, for a forum, a README or a website": "맵으로 연결되는 맵 그림. 포럼, README, 웹사이트에 붙일 수 있습니다",
  "A picture of the map that opens this link, for a forum, a README or a website": "이 링크를 여는 맵 그림 — 포럼, README, 웹사이트용",
  "A picture of “{name}” that links to it, for a forum post or signature, a README or a website. The picture shows the map, its name, who shared it, its size and players.": "“{name}” 맵으로 연결되는 그림입니다. 포럼 글이나 서명, README, 웹사이트에 붙일 수 있습니다. 그림에는 맵과 이름, 공유한 사람, 크기와 플레이어 수가 나옵니다.",
  "A question, or leave empty for a walkthrough of what happens in play.": "질문을 적거나, 비워 두면 게임에서 일어나는 일을 차례로 설명합니다.",
  "A round is one answer from the model followed by the tool calls it asked for; the assistant stops at the limit and offers to continue. A picture costs about as much as a page of text each time. Following moves the view to each call's spot and zooms out when the spot is larger than the view, never in; scroll or zoom yourself during a turn and it stops until the next one. The dock setting applies the next time the assistant opens.": "라운드는 모델의 답 하나와 그 답이 요청한 도구 호출입니다. 어시스턴트는 한도에서 멈추고 계속할지 묻습니다. 그림은 보낼 때마다 텍스트 한 쪽 정도의 비용이 듭니다. 따라가기는 화면을 각 호출의 위치로 옮기고, 그 위치가 화면보다 크면 축소합니다(확대는 하지 않습니다). 차례 도중에 직접 스크롤하거나 확대/축소하면 다음 차례까지 따라가기가 멈춥니다. 도킹 설정은 다음에 어시스턴트를 열 때 적용됩니다.",
  "A trial is one browser, once. Sign in to keep what is left, get the sign-in credit, and store maps.": "체험은 브라우저 하나에서 한 번만 됩니다. 로그인하면 남은 잔액을 유지하고, 로그인 크레딧을 받고, 맵을 보관할 수 있습니다.",
  "AI Assistant": "AI 어시스턴트",
  "AI Assistant (Ctrl+Shift+A)": "AI 어시스턴트 (Ctrl+Shift+A)",
  "AI Assistant · {name}": "AI 어시스턴트 · {name}",
  "AI activity": "AI 작업",
  "AI features": "AI 기능",
  "AI · {phase}": "AI · {phase}",
  "AI · {phase} · {detail}": "AI · {phase} · {detail}",
  "AI: Ask about this": "AI: 이것에 대해 묻기",
  "AI: Assistant": "AI: 어시스턴트",
  "AI: Generate Map": "AI: 맵 생성",
  "AI: Make Scenario": "AI: 시나리오 만들기",
  "AI: Options": "AI: 옵션",
  "AI: built {n, plural, one {# trigger} other {# triggers}} from the script.": "AI: 스크립트로 트리거 {n, plural, other {#개를}} 빌드했습니다.",
  "AI: keeper for player {slot}": "AI: 플레이어 {slot} 유지 유닛",
  "AI: mission briefing": "AI: 임무 브리핑",
  "AI: name and description": "AI: 이름과 설명",
  "AI: objectives": "AI: 목표",
  "AI: players and forces": "AI: 플레이어와 세력",
  "AI: redo area": "AI: 영역 다시 만들기",
  "AI: rewrite strings": "AI: 문자열 다시 쓰기",
  "AI: start locations": "AI: 시작 위치",
  "AI: the area is too small to redo.": "AI: 다시 만들기에는 영역이 너무 작습니다.",
  "AI: {name}": "AI: {name}",
  "AI: {name} terrain": "AI: {name} 지형",
  "AI: {summary}": "AI: {summary}",
  "About the mission briefing: ": "임무 브리핑에 대해: ",
  "About the triggers: ": "트리거에 대해: ",
  "Account": "계정",
  "Account ▸ My Maps… lists the map's links, how often each was opened, and removes them.": "계정 ▸ 내 맵…에서 맵의 링크와 각 링크가 열린 횟수를 보고 링크를 제거할 수 있습니다.",
  "Account…": "계정…",
  "Add a note…": "메모 추가…",
  "Add a string: \"{text}\"": "문자열 추가: \"{text}\"",
  "Add location \"{name}\" at {rect}": "로케이션 \"{name}\" 추가 ({rect})",
  "Add the sound {path}": "사운드 {path} 추가",
  "Add triggers from text": "텍스트에서 트리거 추가",
  "Add {n, plural, one {# briefing trigger} other {# briefing triggers}} from text": "텍스트에서 브리핑 트리거 {n}개 추가",
  "Add {n, plural, one {# trigger} other {# triggers}} from text": "텍스트에서 트리거 {n}개 추가",
  "After": "이후",
  "Amount": "금액",
  "Another map is being shared from this editor already.": "이 에디터에서 이미 다른 맵을 공유하고 있습니다.",
  "Anyone who sees this picture can follow it, join the map and edit it. Account ▸ Shared maps ▸ New link stops the old link working.": "이 그림을 보는 사람은 누구나 링크를 따라 맵에 참여해 편집할 수 있습니다. 계정 ▸ 공유 맵 ▸ 새 링크로 이전 링크를 끊을 수 있습니다.",
  "Anyone with one of these links can open a copy of this map in their editor, without signing in. The copy is theirs; nothing they do changes yours.": "이 링크 중 하나만 있으면 누구나 로그인 없이 자기 에디터에서 이 맵의 사본을 열 수 있습니다. 사본은 그 사람의 것이며, 그 사람이 무엇을 하든 내 맵은 바뀌지 않습니다.",
  "Anyone with the link can open this map in their own editor and change it with you, at the same time. Everyone sees the others' changes as they are made, and their pointers on the map.": "링크가 있는 사람은 누구나 자기 에디터에서 이 맵을 열어 동시에 함께 고칠 수 있습니다. 모두가 다른 사람의 변경을 바로 보고, 맵 위의 포인터도 봅니다.",
  "Applied: {summary}. Edit ▸ Undo takes it back.": "적용했습니다: {summary}. 편집 ▸ 실행 취소로 되돌릴 수 있습니다.",
  "Apply": "적용",
  "Apply on top": "위에 적용",
  "Apply ticked": "체크한 항목 적용",
  "Ashworld": "애쉬월드",
  "Ask": "질문",
  "Ask AI about the selection…": "선택한 것에 대해 AI에게 묻기…",
  "Ask AI about this area…": "이 영역에 대해 AI에게 묻기…",
  "Ask AI about this spot…": "이 지점에 대해 AI에게 묻기…",
  "Ask about the map, or say what to change. Enter sends, Shift+Enter for a new line, Esc stops.": "맵에 대해 묻거나 바꿀 내용을 말하세요. Enter로 보내고, Shift+Enter로 줄을 바꾸고, Esc로 멈춥니다.",
  "Ask the AI for a name and description from what is on the map; fills the fields, OK writes them": "맵에 있는 것을 보고 AI에게 이름과 설명을 받습니다. 칸을 채우기만 하고, 확인을 눌러야 저장됩니다",
  "Ask the assistant about the triggers": "어시스턴트에게 트리거에 대해 묻습니다",
  "Asking scmjs.dev": "scmjs.dev에 요청하는 중",
  "Asking…": "묻는 중…",
  "Assistant": "어시스턴트",
  "Assistant: {text}": "어시스턴트: {text}",
  "Auto-place Start Locations": "시작 위치 자동 배치",
  "BBCode — forums": "BBCode — 포럼",
  "Badlands": "배드랜드",
  "Balance": "밸런스",
  "Bases": "기지",
  "Before": "이전",
  "Build": "빌드",
  "Build the script ({n, plural, one {# line} other {# lines}})": "스크립트 빌드 ({n}줄)",
  "Build the script ({n, plural, one {# line} other {# lines}}), replacing every trigger": "스크립트 빌드 ({n}줄), 모든 트리거 대체",
  "Build the waiting systems": "기다리는 시스템 빌드",
  "Build {kind}": "{kind} 만들기",
  "Build {kind}: {params}": "{kind} 만들기: {params}",
  "Builds the map from this design: the terrain first (that is the long step), then the players, the systems, the text.": "이 설계로 맵을 빌드합니다. 먼저 지형(오래 걸리는 단계), 그다음 플레이어, 시스템, 텍스트 순입니다.",
  "Built {n, plural, one {# trigger} other {# triggers}} into the map (#{first}–#{last}). The source is kept with the map; TrigScript shows it.": "트리거 {n, plural, other {#개를}} 맵에 빌드했습니다 (#{first}–#{last}). 소스는 맵과 함께 보관되며 TrigScript에서 볼 수 있습니다.",
  "Built {name} with {parts}.": "{name|을} 빌드했습니다({parts}).",
  "Built {name}, {n} waiting for locations.": "{name|을} 빌드했습니다. {n}개는 로케이션을 기다립니다.",
  "Built {name}.": "{name|을} 빌드했습니다.",
  "Can units walk from {from} to {to} without the bridges?": "다리 없이 유닛이 {from}에서 {to}까지 걸어갈 수 있나요?",
  "Can units walk from {from} to {to}?": "유닛이 {from}에서 {to}까지 걸어갈 수 있나요?",
  "Can {unit} go at {x},{y}?": "{x},{y}에 {unit|을} 놓을 수 있나요?",
  "Cancel": "취소",
  "Change the design first": "먼저 설계 바꾸기",
  "Changing the design": "설계를 바꾸는 중",
  "Chat": "채팅",
  "Chat with the people on this shared map": "이 공유 맵에 있는 사람들과 채팅",
  "Chat · shared map": "채팅 · 공유 맵",
  "Chat · {name}": "채팅 · {name}",
  "Check": "검사",
  "Check Map": "맵 검사",
  "Check Map: {text}": "맵 검사: {text}",
  "Check the game's rules": "게임 규칙 검사",
  "Check the game's rules and fix what fails": "게임 규칙을 검사하고 어긋난 것 고치기",
  "Check the map": "맵 검사",
  "Clear": "지우기",
  "Clear the selection": "선택 해제",
  "Clear {rect} for player {players}": "플레이어 {players}의 {rect} 안개 지우기",
  "Clear {rect} for players {players}": "플레이어 {players}의 {rect} 안개 지우기",
  "Click for your account.": "클릭하면 계정을 엽니다.",
  "Click to enlarge": "클릭하면 확대합니다",
  "Click to see the link and who is in.": "클릭하면 링크와 참여한 사람을 봅니다.",
  "Close": "닫기",
  "Compiler: {message}": "컴파일러: {message}",
  "Compiles: {n, plural, one {# trigger} other {# triggers}}, {programs, plural, one {a program} other {# programs}} of {inPrograms, plural, one {# trigger} other {# triggers}}.": "컴파일됨: 트리거 {n, plural, other {#개}}, 프로그램 {programs, plural, other {#개}}(트리거 {inPrograms, plural, other {#개}}).",
  "Compiles: {n, plural, one {# trigger} other {# triggers}}.": "컴파일됨: 트리거 {n, plural, other {#개}}.",
  "Connecting…": "연결하는 중…",
  "Continue": "계속",
  "Convert {n, plural, one {# doodad} other {# doodads}} to terrain": "장식물 {n}개를 지형으로 변환",
  "Copy": "복사",
  "Copy Link to This Map": "이 맵의 링크 복사",
  "Copy Link to This Map…": "이 맵의 링크 복사…",
  "Copy link": "링크 복사",
  "Copy the transcript as text": "대화 내용을 텍스트로 복사",
  "Copying the map to scmjs.dev…": "맵을 scmjs.dev에 복사하는 중…",
  "Could not reach the shared map.": "공유 맵에 연결하지 못했습니다.",
  "Death counters and switches": "데스 카운터와 스위치",
  "Delete": "삭제",
  "Delete map": "맵 삭제",
  "Delete map…": "맵 삭제…",
  "Delete revision": "버전 삭제",
  "Delete revision #{n}": "버전 #{n} 삭제",
  "Delete revision #{n} of {name}? Its file is removed from the account when no other revision shares it.": "{name}의 #{n} 버전을 삭제할까요? 다른 버전이 같은 파일을 쓰지 않으면 파일이 계정에서 지워집니다.",
  "Delete revision #{n} of {name}? Its file is removed from the account when no other revision shares it. {links, plural, one {The link to it stops} other {The # links to it stop}} working too.": "{name}의 #{n} 버전을 삭제할까요? 다른 버전이 같은 파일을 쓰지 않으면 파일이 계정에서 지워집니다. 이 버전을 가리키는 링크 {links}개도 더 이상 작동하지 않습니다.",
  "Delete {name} and all {revisions} of its revisions from the account?": "{name|과} 버전 {revisions}개를 모두 계정에서 삭제할까요?",
  "Delete {name} and all {revisions} of its revisions from the account? {links, plural, one {Its link stops} other {Its # links stop}} working too.": "{name|과} 버전 {revisions}개를 모두 계정에서 삭제할까요? 링크 {links}개도 더 이상 작동하지 않습니다.",
  "Deleting…": "삭제하는 중…",
  "Describe": "설명",
  "Description": "설명",
  "Desert": "사막",
  "Design": "설계",
  "Design again": "다시 설계",
  "Designer's notes": "디자이너 메모",
  "Designing the scenario": "시나리오를 설계하는 중",
  "Diagonal mirror (square)": "대각선 대칭 (정사각형)",
  "Dock the assistant at the right, under the Properties panel, instead of floating over the map": "어시스턴트를 맵 위에 띄우지 않고 오른쪽 속성 패널 아래에 도킹",
  "Done in {s} s": "{s}초 만에 완료",
  "Done.": "완료.",
  "Download": "다운로드",
  "Downloading #{n}…": "#{n} 내려받는 중…",
  "Downloading…": "내려받는 중…",
  "Drag over the area to redo": "다시 만들 영역을 드래그하세요",
  "Edit location #{index}: {parts}": "로케이션 #{index} 편집: {parts}",
  "Edit note…": "메모 편집…",
  "Eight-fold (square)": "8방향 (정사각형)",
  "Embed This Map": "이 맵 퍼가기",
  "Embed…": "퍼가기…",
  "End sharing": "공유 끝내기",
  "End sharing this map? Everyone is sent out of it and the link stops working. The map and its revisions stay in My Maps.": "이 맵의 공유를 끝낼까요? 모두가 나가게 되고 링크는 더 이상 작동하지 않습니다. 맵과 버전은 내 맵에 남습니다.",
  "End sharing {name}? Anyone in it is sent out and the link stops working. The map and its revisions stay here.": "{name} 공유를 끝낼까요? 안에 있는 사람은 모두 나가게 되고 링크는 더 이상 작동하지 않습니다. 맵과 버전은 여기에 남습니다.",
  "End sharing “{name}”? Anyone in it is sent out and the link stops working. The map and its revisions stay in My Maps.": "“{name}” 공유를 끝낼까요? 안에 있는 사람은 모두 나가게 되고 링크는 더 이상 작동하지 않습니다. 맵과 버전은 내 맵에 남습니다.",
  "End sharing “{name}”? Anyone in it is sent out; they keep their copy and can save it.": "“{name}” 공유를 끝낼까요? 안에 있는 사람은 모두 나가게 되지만, 각자 사본을 가지고 있어 저장할 수 있습니다.",
  "Ending sharing…": "공유를 끝내는 중…",
  "Ends {date} unless someone edits it": "누군가 편집하지 않으면 {date}에 끝남",
  "Every string in use": "사용 중인 모든 문자열",
  "Every version of StarCraft (triggers only)": "모든 버전의 스타크래프트 (트리거만)",
  "Example: four-player lake": "예: 4인용 호수",
  "Example: tight badlands": "예: 좁은 배드랜드",
  "Example: two-player jungle": "예: 2인용 정글",
  "Explain": "설명",
  "Explain Triggers": "트리거 설명",
  "Explain Triggers…": "트리거 설명…",
  "Extend the map's current script": "맵의 현재 스크립트에 덧붙이기",
  "Failed": "실패",
  "Find \"{text}\" in the locations": "로케이션에서 \"{text}\" 찾기",
  "Find \"{text}\" in the sprites": "스프라이트에서 \"{text}\" 찾기",
  "Find \"{text}\" in the strings": "문자열에서 \"{text}\" 찾기",
  "Find \"{text}\" in the triggers": "트리거에서 \"{text}\" 찾기",
  "Find \"{text}\" in the units": "유닛에서 \"{text}\" 찾기",
  "Find {w} × {h} of flat ground near the centre": "중앙 부근에서 {w} × {h} 평지 찾기",
  "Find {w} × {h} of flat ground near {x},{y}": "{x},{y} 부근에서 {w} × {h} 평지 찾기",
  "Find {w} × {h} of open ground near the centre": "중앙 부근에서 {w} × {h} 빈 땅 찾기",
  "Find {w} × {h} of open ground near {x},{y}": "{x},{y} 부근에서 {w} × {h} 빈 땅 찾기",
  "Fit a bridge near {x},{y}": "{x},{y} 부근에 다리 맞추기",
  "Fit a ramp near {x},{y} facing south-east": "{x},{y} 부근에 남동쪽을 향한 경사로 맞추기",
  "Fit a ramp near {x},{y} facing south-west": "{x},{y} 부근에 남서쪽을 향한 경사로 맞추기",
  "Fix spelling and grammar": "맞춤법과 문법 고치기",
  "Fog": "안개",
  "Fog {rect} for player {players}": "플레이어 {players}의 {rect} 안개 덮기",
  "Fog {rect} for players {players}": "플레이어 {players}의 {rect} 안개 덮기",
  "Follow the assistant's work around the map": "맵에서 어시스턴트의 작업 따라가기",
  "For a day": "하루 동안",
  "For a month": "한 달 동안",
  "For a week": "일주일 동안",
  "Force {index} \"{name}\"": "세력 {index} \"{name}\"",
  "Forces": "세력",
  "Forget the conversation": "대화 내용 지우기",
  "Free trial": "무료 체험",
  "Free trial · {balance} left · sign in to keep it and get more": "무료 체험 · {balance} 남음 · 로그인하면 유지되고 더 받을 수 있습니다",
  "From – to": "범위",
  "Game Data (getting the game's graphics)": "게임 데이터 (게임 그래픽 받는 중)",
  "Generate": "생성",
  "Generate Map": "맵 생성",
  "Generate Map…": "맵 생성…",
  "Go to": "이동",
  "Go to location #{n}": "로케이션 #{n|로} 이동",
  "Go to unit #{n}": "유닛 #{n|로} 이동",
  "Go to {x},{y}": "{x},{y|로} 이동",
  "Green: the toolkit builds it from the parameters. Gold: written as a trigger script from the description. Edit the parameters here; a location or unit by name, numbers as digits.": "초록: 툴킷이 매개변수로 만듭니다. 금색: 설명을 보고 트리거 스크립트로 작성합니다. 매개변수는 여기서 고치세요. 로케이션과 유닛은 이름으로, 수는 숫자로 적습니다.",
  "HTML — websites": "HTML — 웹사이트",
  "How hard the model works on a request, and so how long it takes and what it costs. Standard gives each feature the setting it was tuned for — laying out maps and writing triggers already work at the highest one. Changing it in the middle of an assistant conversation makes the server re-read the whole conversation once; the next message is a little dearer.": "모델이 요청 하나에 얼마나 공을 들이는지, 그래서 얼마나 걸리고 얼마가 드는지를 정합니다. 표준은 기능마다 맞춰 둔 설정을 씁니다. 맵 배치와 트리거 작성은 이미 가장 높은 설정으로 동작합니다. 어시스턴트 대화 도중에 바꾸면 서버가 대화 전체를 한 번 다시 읽으므로 다음 메시지가 조금 더 비쌉니다.",
  "How long it stays open after its last edit": "마지막 편집 후 열어 둘 기간",
  "How the others see you": "다른 사람에게 보일 이름",
  "Ice": "얼음",
  "Import Strings": "문자열 가져오기",
  "Import Triggers": "트리거 가져오기",
  "In it now: {people}": "지금 참여 중: {people}",
  "In-universe": "세계관 말투",
  "Include a picture of the map in the list (one pixel per tile)": "목록에 맵 그림 넣기 (타일당 1픽셀)",
  "Installation": "인스톨레이션",
  "Instruction": "지시",
  "Into": "대상",
  "Into the open map: its terrain and objects are replaced by the plan, and the triggers are appended to what is there.": "열린 맵에: 지형과 오브젝트는 계획으로 교체되고, 트리거는 기존 트리거 뒤에 덧붙습니다.",
  "Into the open map: its terrain and objects inside the plan's area are replaced. One undo step.": "열린 맵에: 계획 영역 안의 지형과 오브젝트가 교체됩니다. 실행 취소 한 단계입니다.",
  "It is yours: File ▸ Save asks where to keep it.": "이제 내 맵입니다. 파일 ▸ 저장을 누르면 보관할 위치를 묻습니다.",
  "Join": "참여",
  "Join a Shared Map": "공유 맵 참여",
  "Join a Shared Map…": "공유 맵 참여…",
  "Join it to edit with whoever is there; Open gives you a copy of a revision on its own.": "참여하면 그 안의 사람들과 함께 편집합니다. 열기는 버전의 사본을 따로 엽니다.",
  "Joined the shared map": "공유 맵에 참여했습니다",
  "Joined “{name}”": "“{name}”에 참여했습니다",
  "Joining {name}…": "{name}에 참여하는 중…",
  "Joining…": "참여하는 중…",
  "Jump to latest": "최신으로 이동",
  "Jungle": "정글",
  "Keep it open": "열어 둘 기간",
  "Keep the units, sprites and doodads that are there now": "지금 있는 유닛, 스프라이트, 장식물 유지",
  "Kept open": "열어 둠",
  "Kept open · {ends}": "열어 둠 · {ends}",
  "Kept open: {ends}. Each time everyone has left, it saves a new revision to the owner's My Maps.": "열어 둠: {ends}. 모두가 나갈 때마다 소유자의 내 맵에 새 버전을 저장합니다.",
  "Kept open: {ends}. Each time everyone has left, it saves a new revision to your My Maps.": "열어 둠: {ends}. 모두가 나갈 때마다 내 맵에 새 버전을 저장합니다.",
  "Kept open: {ends}. Each time everyone has left, it saves a new revision to {owner}'s My Maps.": "열어 둠: {ends}. 모두가 나갈 때마다 {owner}의 내 맵에 새 버전을 저장합니다.",
  "Kept the open map.": "열린 맵을 그대로 두었습니다.",
  "Large (1200 × 630)": "크게 (1200 × 630)",
  "Last edit {when}": "마지막 편집 {when}",
  "Last edit {when} by {name}": "마지막 편집 {when}, {name}",
  "Lay a base": "기지 배치",
  "Lay out the {preset} preset": "{preset} 프리셋 배치",
  "Lay out the {preset} preset: {params}": "{preset} 프리셋 배치: {params}",
  "Layout brief and {n, plural, one {# location} other {# locations}}": "배치 개요와 로케이션 {n, plural, other {#개}}",
  "Leave": "나가기",
  "Let the link follow my later saves to this map": "이후 이 맵에 저장한 내용을 링크가 따라가게 하기",
  "Let the model choose": "모델이 고르게 하기",
  "Link": "링크",
  "Link removed.": "링크를 제거했습니다.",
  "Link to #{n}": "#{n} 링크",
  "Link to the newest": "최신 버전 링크",
  "Link to {which} made and copied.": "{which} 링크를 만들어 복사했습니다.",
  "Link to {which} made.": "{which} 링크를 만들었습니다.",
  "Links": "링크",
  "List": "목록",
  "List the guides": "가이드 목록",
  "List units": "유닛 목록",
  "List {owner}'s units": "{owner}의 유닛 목록",
  "Load the list again": "목록을 다시 불러옵니다",
  "Loading your maps…": "맵을 불러오는 중…",
  "Loading your shared maps…": "공유 중인 맵을 불러오는 중…",
  "Location Properties": "로케이션 속성",
  "Locations": "로케이션",
  "Locations the brief must place": "개요가 배치해야 할 로케이션",
  "Look up the AI script \"{query}\"": "AI 스크립트 \"{query}\" 찾아보기",
  "Look up the action \"{query}\"": "액션 \"{query}\" 찾아보기",
  "Look up the condition \"{query}\"": "조건 \"{query}\" 찾아보기",
  "Look up the doodad \"{query}\"": "장식물 \"{query}\" 찾아보기",
  "Look up the sprite \"{query}\"": "스프라이트 \"{query}\" 찾아보기",
  "Look up the tech \"{query}\"": "기술 \"{query}\" 찾아보기",
  "Look up the unit \"{query}\"": "유닛 \"{query}\" 찾아보기",
  "Look up the upgrade \"{query}\"": "업그레이드 \"{query}\" 찾아보기",
  "Look up the weapon \"{query}\"": "무기 \"{query}\" 찾아보기",
  "Look up the {kind} \"{query}\"": "{kind} \"{query}\" 찾아보기",
  "Looking it up…": "찾는 중…",
  "Made {date}": "{date}에 만듦",
  "Make Scenario": "시나리오 만들기",
  "Make Scenario…": "시나리오 만들기…",
  "Making a link…": "링크를 만드는 중…",
  "Making the link…": "링크를 만드는 중…",
  "Manage": "관리",
  "Manage on scmjs.dev": "scmjs.dev에서 관리",
  "Map Properties": "맵 속성",
  "Map Revision": "맵 버전",
  "Map deleted.": "맵을 삭제했습니다.",
  "Map storage": "맵 저장 공간",
  "Maps are kept on a signed-in account; a trial cannot store them.": "맵은 로그인한 계정에 보관됩니다. 체험으로는 보관할 수 없습니다.",
  "Maps you save to scmjs.dev show up here, with every revision and its note.": "scmjs.dev에 저장한 맵이 모든 버전과 메모와 함께 여기에 나타납니다.",
  "Markdown — GitHub, Discourse, Reddit": "Markdown — GitHub, Discourse, Reddit",
  "Melee balance": "밀리 밸런스",
  "Mirror both ways": "양축 대칭",
  "Mirror left ↔ right": "좌우 대칭",
  "Mirror top ↔ bottom": "상하 대칭",
  "Mission Briefing": "임무 브리핑",
  "Mission briefing": "임무 브리핑",
  "Mission briefing ({n})": "임무 브리핑 ({n})",
  "Move trigger #{from} to #{to}": "트리거 #{from} 위치를 #{to|로} 이동",
  "Move {n, plural, one {# unit} other {# units}}": "유닛 {n}개 이동",
  "My Maps on scmjs.dev": "scmjs.dev의 내 맵",
  "My Maps on scmjs.dev…": "scmjs.dev의 내 맵…",
  "My Maps…": "내 맵…",
  "Name": "이름",
  "Name and Describe": "이름과 설명 짓기",
  "Name and Describe…": "이름과 설명 짓기…",
  "Name and description": "이름과 설명",
  "Name for this map:": "이 맵의 이름:",
  "Name in the list": "목록에 보일 이름",
  "Name switch {index} \"{name}\"": "스위치 {index} 이름 지정: \"{name}\"",
  "Narration": "내레이션",
  "Neutral": "중립",
  "New link": "새 링크",
  "Newest": "최신",
  "No links. A link lets anyone open a copy of this map in their editor, without signing in.": "링크가 없습니다. 링크가 있으면 누구나 로그인 없이 자기 에디터에서 이 맵의 사본을 열 수 있습니다.",
  "No map is open.": "열린 맵이 없습니다.",
  "No map matches \"{query}\".": "\"{query}\"에 맞는 맵이 없습니다.",
  "No maps yet": "아직 맵이 없습니다",
  "No note": "메모 없음",
  "No strings in that scope.": "그 범위에는 문자열이 없습니다.",
  "Nobody in it now": "지금 아무도 없음",
  "None": "없음",
  "Not built: the script has errors.": "빌드하지 않음: 스크립트에 오류가 있습니다.",
  "Not opened.": "열지 않았습니다.",
  "Not saved.": "저장하지 않았습니다.",
  "Not signed in": "로그인 안 함",
  "Not signed in to scmjs.dev. Click to sign in.": "scmjs.dev에 로그인하지 않았습니다. 클릭하면 로그인합니다.",
  "Not signed in · the first AI request starts a free trial": "로그인 안 함 · 첫 AI 요청 때 무료 체험이 시작됩니다",
  "Note": "메모",
  "Note for revision #{n} of {name}:": "{name}의 버전 #{n} 메모:",
  "Note for this revision": "이 버전의 메모",
  "Note saved.": "메모를 저장했습니다.",
  "Nothing changed.": "바뀐 것이 없습니다.",
  "Nothing said yet. Everyone on the shared map sees what you write here; it goes when the sharing ends.": "아직 아무 말도 없습니다. 여기에 쓴 내용은 공유 맵에 있는 모두가 보며, 공유가 끝나면 사라집니다.",
  "Nothing spent this session.": "이번 세션에서 쓴 금액이 없습니다.",
  "Now: \"{name}\" — {description}": "현재: \"{name}\" — {description}",
  "Objectives": "목표",
  "Objectives and briefing": "목표와 브리핑",
  "Objectives, one per line.": "목표, 한 줄에 하나씩.",
  "Off": "끔",
  "Off for now while I work out the tooling and costs.": "도구와 비용을 정리하는 동안 잠시 꺼 두었습니다.",
  "Off leaves your account and the maps stored on it; Tools ▸ AI ▸ Options… has the quality and the assistant's settings.": "꺼도 계정과 계정에 보관된 맵은 그대로 남습니다. 품질과 어시스턴트 설정은 도구 ▸ AI ▸ 옵션…에 있습니다.",
  "Off takes the Tools ▸ AI menu, the assistant and the AI buttons in the editor's dialogs away. Your account and the maps stored on it stay.": "끄면 도구 ▸ AI 메뉴, 어시스턴트, 에디터 대화 상자의 AI 버튼이 사라집니다. 계정과 계정에 저장한 맵은 그대로 남습니다.",
  "On": "켬",
  "One undo step.": "실행 취소 한 단계입니다.",
  "Only names: scenario, forces, units, locations, switches": "이름만: 시나리오, 세력, 유닛, 로케이션, 스위치",
  "Only the mission briefing": "임무 브리핑만",
  "Only trigger text (messages, objectives)": "트리거 텍스트만 (메시지, 목표)",
  "Open": "열기",
  "Open #{n}": "#{n} 열기",
  "Open TrigScript": "TrigScript 열기",
  "Open a Copy": "사본 열기",
  "Open a Map Link…": "맵 링크 열기…",
  "Open a copy": "사본 열기",
  "Open a map first.": "먼저 맵을 여세요.",
  "Open from scmjs.dev…": "scmjs.dev에서 열기…",
  "Open revision #{n} in the editor": "#{n} 버전을 에디터에서 엽니다",
  "Open the assistant": "어시스턴트 열기",
  "Open the shared map and edit it with whoever is in it": "공유 맵을 열고 그 안에 있는 사람들과 함께 편집합니다",
  "Open this revision on its own, apart from the shared map": "공유 맵과 별개로 이 버전만 따로 엽니다",
  "Open until everyone leaves": "모두 나갈 때까지 열림",
  "Opened a copy of {name}": "{name} 사본을 열었습니다",
  "Opened {name} #{n}": "{name} #{n} 열림",
  "Options…": "옵션…",
  "Or: {names}": "다른 안: {names}",
  "Other diagonal (square)": "반대 대각선 대칭 (정사각형)",
  "Other edits came after this turn's; undo them first, from the Edit menu.": "이 차례 뒤에 다른 편집이 있습니다. 편집 메뉴에서 그 편집들을 먼저 실행 취소하세요.",
  "Packing the map…": "맵을 묶는 중…",
  "Paint shapes": "도형 칠하기",
  "Paint {n, plural, one {# shape} other {# shapes}}: {list}": "도형 {n}개 칠하기: {list}",
  "Paint {terrain} over {rect}": "{rect}에 {terrain} 칠하기",
  "Paste the link you were sent": "받은 링크를 붙여 넣으세요",
  "People on the shared map": "공유 맵의 사람들",
  "Per Make Scenario run ($)": "시나리오 만들기 실행당 ($)",
  "Per assistant message ($)": "어시스턴트 메시지당 ($)",
  "Pick a map to see its revisions.": "맵을 고르면 버전이 보입니다.",
  "Picture": "그림",
  "Place doodads": "장식물 배치",
  "Place sprites": "스프라이트 배치",
  "Place sprites: {sprites} near {x},{y}": "스프라이트 배치: {sprites} ({x},{y} 부근)",
  "Place units": "유닛 배치",
  "Place {doodads} near {x},{y}": "{doodads} 배치 ({x},{y} 부근)",
  "Place {units} for {owner} near {x},{y}": "{owner}의 {units} 배치 ({x},{y} 부근)",
  "Planning the terrain": "지형을 계획하는 중",
  "Player Colors": "플레이어 색상",
  "Player Settings": "플레이어 설정",
  "Player {n}": "플레이어 {n}",
  "Player {slot}: {type}, {race}, force {force} — {role}": "플레이어 {slot}: {type}, {race}, 세력 {force} — {role}",
  "Players": "플레이어",
  "Players and forces": "플레이어와 세력",
  "Plays on": "실행 환경",
  "Preserve {n, plural, one {# trigger} other {# triggers}}": "트리거 {n}개 유지",
  "Put #{n} in": "#{n} 넣기",
  "Put #{n} into the shared map": "공유 맵에 #{n} 넣기",
  "Put a revision into the shared map": "공유 맵에 버전 넣기",
  "Quality": "품질",
  "Quick — fastest and cheapest": "빠르게 — 가장 빠르고 가장 저렴함",
  "Read Player {player}'s fog": "플레이어 {player}의 안개 읽기",
  "Read Player {player}'s fog over {rect}": "플레이어 {player}의 {rect} 안개 읽기",
  "Read the guide: {id}": "가이드 읽기: {id}",
  "Read the map's bases": "맵의 기지 읽기",
  "Read the terrain at {x},{y}": "{x},{y} 지형 읽기",
  "Read the terrain over {rect}": "{rect} 지형 읽기",
  "Read {what, select, briefing {the briefing} other {the triggers}}{range} as text": "{what, select, briefing {브리핑} other {트리거}}{range} 텍스트로 읽기",
  "Ready": "준비됨",
  "Ready.": "준비됨.",
  "Reasoning": "추론",
  "Recent activity": "최근 사용 내역",
  "Reconnected to the shared map.": "공유 맵에 다시 연결했습니다.",
  "Reconnecting…": "다시 연결하는 중…",
  "Redo Area {x0},{y0} – {x1},{y1}": "영역 다시 만들기 {x0},{y0} – {x1},{y1}",
  "Redo Area…": "영역 다시 만들기…",
  "Redo this area with AI…": "AI로 이 영역 다시 만들기…",
  "Refills": "충전",
  "Refills {date}": "{date}에 다시 채워짐",
  "Refine": "다듬기",
  "Refresh": "새로 고침",
  "Refreshing…": "새로 고치는 중…",
  "Remove": "제거",
  "Remove link": "링크 제거",
  "Remove this link to {name}? Anyone who has it can no longer open the map. The map stays on your account.": "{name} 맵의 이 링크를 제거할까요? 링크를 가진 사람은 더 이상 맵을 열 수 없습니다. 맵은 계정에 그대로 남습니다.",
  "Remove {n, plural, one {# doodad} other {# doodads}} {list}": "장식물 {n}개 제거 {list}",
  "Remove {n, plural, one {# location} other {# locations}} {list}": "로케이션 {n}개 제거 {list}",
  "Remove {n, plural, one {# sprite} other {# sprites}}": "스프라이트 {n}개 제거",
  "Remove {n, plural, one {# trigger} other {# triggers}} {list}": "트리거 {n}개 제거 {list}",
  "Remove {n, plural, one {# unit} other {# units}} {list}": "유닛 {n}개 제거 {list}",
  "Rename": "이름 바꾸기",
  "Rename map": "맵 이름 바꾸기",
  "Renamed.": "이름을 바꿨습니다.",
  "Rename…": "이름 바꾸기…",
  "Renaming…": "이름 바꾸는 중…",
  "Rendering the map at {ppt} px per tile…": "타일당 {ppt}px로 맵을 그리는 중…",
  "Renders the plan onto the map as one undo step, then names the map after it.": "계획을 실행 취소 한 단계로 맵에 그린 다음, 맵 이름을 계획에 맞춰 짓습니다.",
  "Replace Terrain": "지형 바꾸기",
  "Replace every trigger on the map with the script (the hand-made ones are folded into it first)": "맵의 모든 트리거를 스크립트로 교체 (직접 만든 트리거는 먼저 스크립트에 합칩니다)",
  "Replace the map's existing briefing": "맵의 기존 브리핑 교체",
  "Replace the shared map with revision #{n}? Everyone in it gets #{n} at once, and everyone's undo history starts again, as after a resize. The map as it is now is not kept unless you save it first.": "공유 맵을 #{n} 버전으로 바꿀까요? 안에 있는 모두에게 즉시 #{n} 버전이 적용되고, 크기 변경 후처럼 모두의 실행 취소 기록이 처음부터 시작됩니다. 먼저 저장하지 않으면 지금의 맵은 남지 않습니다.",
  "Replace the shared map with this revision, for everyone in it": "공유 맵을 이 버전으로 바꿉니다. 안에 있는 모두에게 적용됩니다",
  "Replace trigger #{n}": "트리거 #{n} 교체",
  "Resize Map": "맵 크기 변경",
  "Resize the map to {width} × {height}": "맵 크기를 {width} × {height|로} 변경",
  "Review": "검토",
  "Review Map": "맵 검토",
  "Review Map…": "맵 검토…",
  "Review it…": "검토…",
  "Revision #{n} deleted.": "#{n} 버전을 삭제했습니다.",
  "Revision #{n}, saved {ago}": "버전 #{n}, {ago} 저장",
  "Revision note": "버전 메모",
  "Revisions": "버전",
  "Revisions ({n})": "버전 ({n})",
  "Rewrite": "다시 쓰기",
  "Rewrite Strings": "문자열 다시 쓰기",
  "Rewrite Strings…": "문자열 다시 쓰기…",
  "Rewrite with AI…": "AI로 다시 쓰기…",
  "Role": "역할",
  "Rotate 180°": "180° 회전",
  "Rotate 90° (square)": "90° 회전 (정사각형)",
  "Rounds per message": "메시지당 라운드",
  "Save": "저장",
  "Save and make the link": "저장하고 링크 만들기",
  "Save as": "저장 위치",
  "Save revision #{n} as a file": "#{n} 버전을 파일로 저장합니다",
  "Save the open map here…": "열린 맵을 여기에 저장…",
  "Save to scmjs.dev": "scmjs.dev에 저장",
  "Save to scmjs.dev…": "scmjs.dev에 저장…",
  "Saved as {name} #{n}. Anyone with this link can open a copy of it in their editor, without signing in:": "{name} #{n} 버전으로 저장했습니다. 이 링크가 있으면 누구나 로그인 없이 자기 에디터에서 사본을 열 수 있습니다:",
  "Saved to scmjs.dev: {name} #{n}": "scmjs.dev에 저장됨: {name} #{n}",
  "Saved {name}.": "{name} 저장됨.",
  "Saving the map to My Maps…": "맵을 내 맵에 저장하는 중…",
  "Saving the note…": "메모 저장 중…",
  "Saving…": "저장 중…",
  "Say something to everyone here": "여기 있는 모두에게 말하기",
  "Say what kind of map you want first.": "먼저 어떤 맵을 원하는지 적으세요.",
  "Say what kind of scenario you want first.": "먼저 어떤 시나리오를 원하는지 적으세요.",
  "Say what the area should become first.": "먼저 이 영역을 무엇으로 만들지 적으세요.",
  "Say what the triggers should do first.": "먼저 트리거가 무엇을 할지 적으세요.",
  "Say what to do with the strings first.": "먼저 문자열로 무엇을 할지 적으세요.",
  "Scatter {category} over {rect}": "{rect}에 {category} 흩뿌리기",
  "Scenario": "시나리오",
  "Scope": "범위",
  "Screenshot of the whole map": "맵 전체 스크린샷",
  "Screenshot of {rect}": "{rect} 스크린샷",
  "Script: {name}": "스크립트: {name}",
  "Search maps": "맵 검색",
  "Seconds each": "각각의 초",
  "Select the link and copy it.": "링크를 선택해서 복사하세요.",
  "Select the text and copy it.": "텍스트를 선택해서 복사하세요.",
  "Select {things}": "{things} 선택",
  "Selection": "선택",
  "Send": "보내기",
  "Send a picture of the visible area with every message": "메시지마다 보이는 영역의 그림 보내기",
  "Send a picture of the visible area with the message": "메시지와 함께 보이는 영역의 그림 보내기",
  "Send this link to the people you want to edit with. Anyone who has it can join.": "함께 편집할 사람들에게 이 링크를 보내세요. 링크가 있는 사람은 누구나 참여할 수 있습니다.",
  "Sent a {w} × {h} picture ({kb} KB) with the map's facts and {n, plural, one {# Check Map line} other {# Check Map lines}}.": "{w} × {h} 그림({kb} KB)을 맵 정보, 맵 검사 결과 {n, plural, other {#줄과}} 함께 보냈습니다.",
  "Session: {cost} over {n, plural, one {# call} other {# calls}}": "세션: {cost}, {n, plural, other {#회 호출}}",
  "Set force {list}: {fields}": "세력 {list} 설정: {fields}",
  "Set forces {list}: {fields}": "세력 {list} 설정: {fields}",
  "Set player {list}: {fields}": "플레이어 {list} 설정: {fields}",
  "Set players {list}: {fields}": "플레이어 {list} 설정: {fields}",
  "Set string {index}: \"{text}\"": "문자열 {index} 설정: \"{text}\"",
  "Set the map revision to {version}": "맵 버전을 {version|로} 설정",
  "Set the map's description": "맵 설명 설정",
  "Set the map's name": "맵 이름 설정",
  "Set the map's name and description": "맵 이름과 설명 설정",
  "Set the map's properties": "맵 속성 설정",
  "Set up the players and forces for: ": "다음에 맞게 플레이어와 세력 설정: ",
  "Set up with AI…": "AI로 설정…",
  "Set {fields} on {n, plural, one {# unit} other {# units}}": "유닛 {n}개의 {fields} 설정",
  "Settings": "설정",
  "Share this Map": "이 맵 공유",
  "Share this Map…": "이 맵 공유…",
  "Shared by {owner}": "공유한 사람: {owner}",
  "Shared editing": "공유 편집",
  "Shared editing ended": "함께 편집하기가 끝났습니다",
  "Shared map": "공유 맵",
  "Shared map opened again": "공유 맵을 다시 열었습니다",
  "Shared maps": "공유 맵",
  "Shared {when}": "공유 {when}",
  "Shared · {ends}": "공유 중 · {ends}",
  "Shared · {n, plural, one {# person} other {# people}}": "공유 중 · {n}명",
  "Shared · {n} editing": "공유 중 · {n}명 편집 중",
  "Sharing a map takes a scmjs.dev account. The people you share it with need only the link.": "맵을 공유하려면 scmjs.dev 계정이 필요합니다. 함께할 사람들은 링크만 있으면 됩니다.",
  "Sharing ended.": "공유를 끝냈습니다.",
  "Sharing…": "공유하는 중…",
  "Shorten": "줄이기",
  "Show my status in the status bar": "상태 표시줄에 내 상태 표시",
  "Show the model's reasoning summary while it works": "모델이 작업하는 동안 추론 요약 보기",
  "Sign in": "로그인",
  "Sign in to scmjs.dev": "scmjs.dev에 로그인",
  "Sign in to scmjs.dev to keep maps on your account.": "계정에 맵을 보관하려면 scmjs.dev에 로그인하세요.",
  "Sign in to scmjs.dev…": "scmjs.dev에 로그인…",
  "Sign in to use": "로그인하면 사용 가능",
  "Sign in with {provider}": "{provider|으로} 로그인",
  "Sign in…": "로그인…",
  "Sign out": "로그아웃",
  "Sign out of scmjs.dev": "scmjs.dev에서 로그아웃",
  "Sign-in": "로그인 수단",
  "Signed in": "로그인됨",
  "Signed in as": "로그인 계정",
  "Signed in as {name}.": "{name} 계정으로 로그인했습니다.",
  "Signed in to scmjs.dev": "scmjs.dev에 로그인했습니다",
  "Signed in to scmjs.dev as {name}": "scmjs.dev에 {name} 계정으로 로그인했습니다",
  "Signed in.": "로그인했습니다.",
  "Signed out of scmjs.dev": "scmjs.dev에서 로그아웃했습니다",
  "Signed out.": "로그아웃했습니다.",
  "Signing in {gives}, and room to keep maps on your account.": "로그인하면 {gives|을} 받고, 계정에 맵을 보관할 공간도 생깁니다.",
  "Simulate the triggers for {n, plural, one {# cycle} other {# cycles}}": "트리거 {n}사이클 시뮬레이션",
  "Size": "크기",
  "Small (600 × 315), for a signature": "작게 (600 × 315), 서명용",
  "Someone else's change came first; {n, plural, one {# part} other {# parts}} of yours no longer applied.": "다른 사람의 변경이 먼저 적용되어 내 변경 중 {n}개 부분이 더 이상 적용되지 않았습니다.",
  "Space Platform": "우주 플랫폼",
  "Spending": "지출",
  "Sprite Properties": "스프라이트 속성",
  "Standard — tuned for each feature (recommended)": "표준 — 기능마다 맞춘 설정 (권장)",
  "StarCraft: Remastered (scripts may be programs)": "스타크래프트: 리마스터 (스크립트에 프로그램 사용 가능)",
  "Start sharing": "공유 시작",
  "Start the free trial": "무료 체험 시작",
  "Status": "상태",
  "Step {n} · {text}": "{n}단계 · {text}",
  "Stop": "정지",
  "Stop preserving {n, plural, one {# trigger} other {# triggers}}": "트리거 {n}개 유지 해제",
  "Stop sharing": "공유 중지",
  "Stop sharing this map? Everyone is sent out of it; they keep their copy and can save it.": "이 맵의 공유를 중지할까요? 모두가 나가게 되지만, 각자 사본을 가지고 있어 저장할 수 있습니다.",
  "Stop the build": "빌드 중지",
  "Stopped": "정지됨",
  "Stopped before anything was sent.": "보내기 전에 멈췄습니다.",
  "Stopped building {name}: {parts}. What was built stays.": "{name} 빌드를 멈췄습니다: {parts}. 빌드된 것은 남습니다.",
  "Stopped.": "중지했습니다.",
  "Suggest": "제안",
  "Suggest a name": "이름 제안",
  "Switches": "스위치",
  "Symmetry": "대칭",
  "System: {name}": "시스템: {name}",
  "Systems ({n})": "시스템 ({n})",
  "Talking to {server} — a development server named by ?{query}= on the editor's address. Open the editor with ?{query}= (empty) to go back to scmjs.dev.": "{server}에 연결 중입니다. 에디터 주소의 ?{query}= 값으로 지정한 개발 서버입니다. scmjs.dev로 돌아가려면 에디터를 ?{query}= (빈 값)으로 여세요.",
  "Tech Settings": "기술 설정",
  "Technology settings for {tech}: {fields}": "{tech} 기술 설정: {fields}",
  "Tell the assistant what the players should be": "플레이어를 어떻게 둘지 어시스턴트에게 알려 줍니다",
  "Terrain": "지형",
  "Terrain and locations": "지형과 로케이션",
  "Terrain and locations ({preset} preset)": "지형과 로케이션 ({preset} 프리셋)",
  "That is not a map link.": "맵 링크가 아닙니다.",
  "That is not a shared map's link.": "공유 맵의 링크가 아닙니다.",
  "The TrigScript plugin is off. Turn it on under Plugins ▸ Manage Plugins… to write, check or build trigger scripts.": "TrigScript 플러그인이 꺼져 있습니다. 트리거 스크립트를 쓰거나 검사하거나 빌드하려면 플러그인 ▸ 플러그인 관리…에서 켜세요.",
  "The TrigScript plugin is on: systems the toolkit cannot build are written as scripts.": "TrigScript 플러그인이 켜져 있습니다. 툴킷이 만들 수 없는 시스템은 스크립트로 작성합니다.",
  "The Trigger Script plugin is off: the design will use only the toolkit's systems (hyper triggers, spawns, kill-to-cash, waves, lives, shops, …). Turn it on under Plugins ▸ Manage Plugins… for custom mechanics.": "Trigger Script 플러그인이 꺼져 있습니다. 설계는 툴킷의 시스템(하이퍼 트리거, 스폰, 킬 보상, 웨이브, 목숨, 상점 등)만 씁니다. 직접 만든 규칙이 필요하면 플러그인 ▸ 플러그인 관리…에서 켜세요.",
  "The balance is used up: {message}": "잔액을 다 썼습니다: {message}",
  "The clipboard is not available here.": "여기서는 클립보드를 쓸 수 없습니다.",
  "The connection to the shared map dropped. Keep working: your changes are kept here and sent once it is back. The editor keeps trying for two minutes.": "공유 맵과의 연결이 끊겼습니다. 계속 작업하세요. 변경 내용은 여기에 보관했다가 연결되면 보냅니다. 에디터는 2분 동안 다시 시도합니다.",
  "The connection to the shared map was lost. The map is still open here; save it, or join again.": "공유 맵과의 연결이 끊겼습니다. 맵은 여기에 그대로 열려 있으니 저장하거나 다시 참여하세요.",
  "The design": "설계",
  "The design is for Remastered, and its timers are counted at 24 trigger cycles a second, but no script on the map has a program: until one does the triggers run every two seconds and every timer is about 48 times slow. Add a program in TrigScript, or set the design to every version and build again.": "설계가 리마스터용이라 타이머를 초당 24회 트리거 실행으로 셌지만, 맵의 어떤 스크립트에도 프로그램이 없습니다. 프로그램이 생기기 전까지 트리거는 2초마다 실행되어 모든 타이머가 약 48배 느려집니다. TrigScript에서 프로그램을 추가하거나, 설계를 모든 버전용으로 바꾸고 다시 빌드하세요.",
  "The file is what File ▸ Save would write, with the options you last saved with. Saving the same bytes again costs no storage; only the note is new.": "파일은 마지막으로 저장할 때의 옵션으로 파일 ▸ 저장이 쓰는 것과 같습니다. 같은 내용을 다시 저장하면 저장 공간을 쓰지 않고 메모만 새로 남습니다.",
  "The first AI request starts a free trial with no sign-in. Signing in keeps the balance across browsers and adds the sign-in credit; the Account dialog has the balance, the top-up and the activity.": "첫 AI 요청을 하면 로그인 없이 무료 체험이 시작됩니다. 로그인하면 잔액이 브라우저 사이에서 유지되고 로그인 크레딧이 더해집니다. 잔액, 충전, 사용 내역은 계정 대화 상자에 있습니다.",
  "The link always opens this revision.": "이 링크는 항상 이 버전을 엽니다.",
  "The link is on the clipboard.": "링크를 클립보드에 복사했습니다.",
  "The link opens whichever revision is newest when it is opened.": "이 링크는 열 때 가장 최신인 버전을 엽니다.",
  "The map could not be copied.": "맵을 복사하지 못했습니다.",
  "The map in front changed while the scenario was being built, so the build stopped there: nothing is written into a map it did not start on. Bring the map back to the front and build again; what was built stays.": "시나리오를 빌드하는 동안 앞에 있는 맵이 바뀌어서 빌드를 멈췄습니다. 빌드를 시작하지 않은 맵에는 아무것도 적지 않습니다. 그 맵을 다시 앞으로 가져와 빌드하세요. 이미 빌드한 것은 남아 있습니다.",
  "The map is on scmjs.dev only while it is shared: sharing ends when you stop it, half an hour after the last person leaves, or when the server restarts. Everyone keeps the map in their editor and can save it.": "맵은 공유되는 동안에만 scmjs.dev에 있습니다. 공유는 직접 중지하거나, 마지막 사람이 나가고 30분이 지나거나, 서버가 다시 시작되면 끝납니다. 모두 자기 에디터에 맵이 남아 있어 저장할 수 있습니다.",
  "The map is saved to My Maps and stays open at its link, so people can come and go. Each time everyone has left, it saves a new revision. It ends after a day with no edits, and the map stays in My Maps.": "맵은 내 맵에 저장되고 링크에서 계속 열려 있어 사람들이 드나들 수 있습니다. 모두가 나갈 때마다 새 버전을 저장합니다. 하루 동안 편집이 없으면 끝나며, 맵은 내 맵에 남습니다.",
  "The map is saved to My Maps and stays open at its link, so people can come and go. Each time everyone has left, it saves a new revision. It ends after a month with no edits, and the map stays in My Maps.": "맵은 내 맵에 저장되고 링크에서 계속 열려 있어 사람들이 드나들 수 있습니다. 모두가 나갈 때마다 새 버전을 저장합니다. 한 달 동안 편집이 없으면 끝나며, 맵은 내 맵에 남습니다.",
  "The map is saved to My Maps and stays open at its link, so people can come and go. Each time everyone has left, it saves a new revision. It ends after a week with no edits, and the map stays in My Maps.": "맵은 내 맵에 저장되고 링크에서 계속 열려 있어 사람들이 드나들 수 있습니다. 모두가 나갈 때마다 새 버전을 저장합니다. 일주일 동안 편집이 없으면 끝나며, 맵은 내 맵에 남습니다.",
  "The map is saved to My Maps and stays open at its link, so people can come and go. Each time everyone has left, it saves a new revision. It stays open until you end it (or after a year with no edits), and the map stays in My Maps.": "맵은 내 맵에 저장되고 링크에서 계속 열려 있어 사람들이 드나들 수 있습니다. 모두가 나갈 때마다 새 버전을 저장합니다. 직접 끝낼 때까지 (또는 1년 동안 편집이 없을 때까지) 열려 있으며, 맵은 내 맵에 남습니다.",
  "The map opens as a new file in your editor. It is your own copy: nothing you change reaches the person who shared it.": "맵은 에디터에서 새 파일로 열립니다. 내 사본이므로 무엇을 바꿔도 공유한 사람에게는 전해지지 않습니다.",
  "The map opens beside the ones you have open. You edit it together with everyone in it; closing it leaves.": "맵은 열려 있는 맵들 옆에 열립니다. 안에 있는 모두와 함께 편집하며, 닫으면 나갑니다.",
  "The map stays open for the others and at its link.": "맵은 다른 사람들에게, 그리고 링크에서 계속 열려 있습니다.",
  "The map was edited since the last plan was applied. Apply the new plan on top of it?": "마지막 계획을 적용한 뒤로 맵이 편집되었습니다. 새 계획을 그 위에 적용할까요?",
  "The model declined this request. {message}": "모델이 이 요청을 거절했습니다. {message}",
  "The model declined.": "모델이 거절했습니다.",
  "The model is given this map's names: {starts, plural, one {# start location} other {# start locations}}, {triggers, plural, one {# existing trigger} other {# existing triggers}}, and every unit, location and switch as it is called here.": "모델은 이 맵의 이름을 받습니다: 시작 위치 {starts, plural, other {#개}}, 기존 트리거 {triggers, plural, other {#개}}, 그리고 여기서 부르는 이름 그대로의 모든 유닛, 로케이션, 스위치.",
  "The model named this tool but did not call it.": "모델이 이 도구를 언급했지만 호출하지는 않았습니다.",
  "The model sees the map's state, your selection and the view with every message.": "메시지마다 모델이 맵의 상태, 선택한 것, 화면을 함께 봅니다.",
  "The model sees: {list}": "모델이 보는 것: {list}",
  "The model service failed: {message}": "모델 서비스에 실패했습니다: {message}",
  "The narration, one message per line.": "내레이션, 한 줄에 메시지 하나씩.",
  "The old link no longer works. Nobody in the map was sent out.": "이전 링크는 더 이상 작동하지 않습니다. 맵 안에 있던 사람은 그대로 있습니다.",
  "The open map": "열린 맵",
  "The open map is saved to your account as a new map, and you get a link anyone can open a copy of it with, without signing in.": "열린 맵을 계정에 새 맵으로 저장하고, 누구나 로그인 없이 사본을 열 수 있는 링크를 받습니다.",
  "The open map is saved to your account as a new revision of {name}, and you get a link anyone can open a copy of it with, without signing in.": "열린 맵을 계정에 {name}의 새 버전으로 저장하고, 누구나 로그인 없이 사본을 열 수 있는 링크를 받습니다.",
  "The payment page opened in a new tab. The credit lands once it is paid.": "결제 페이지를 새 탭에 열었습니다. 결제가 끝나면 크레딧이 들어옵니다.",
  "The people who open it get their own copy. Nothing they change reaches yours; to edit it together, use Share this Map… instead.": "링크를 여는 사람은 각자 사본을 받습니다. 그 사람이 바꾼 내용은 내 맵에 전해지지 않습니다. 함께 편집하려면 대신 이 맵 공유…를 쓰세요.",
  "The person who shared the map ended the session.": "맵을 공유한 사람이 세션을 끝냈습니다.",
  "The picture on its own": "그림만",
  "The picture opens": "그림이 여는 것",
  "The plan": "계획",
  "The revised plan replaces the applied one: the previous render is undone first when nothing else was edited in between.": "고친 계획이 적용된 계획을 대신합니다. 그 사이에 다른 편집이 없었다면 이전 결과를 먼저 실행 취소합니다.",
  "The saved map is built by eudplib and needs Remastered. Every trigger runs each frame, so timers are counted at about 24 cycles a second and the hyper triggers in the list are left out.": "저장한 맵은 eudplib로 빌드되며 리마스터가 필요합니다. 모든 트리거가 매 프레임 실행되므로 타이머는 초당 약 24회로 셈하고, 목록의 하이퍼 트리거는 빠집니다.",
  "The saved map is built by eudplib and needs Remastered. Every trigger runs each frame, so timers are counted at about 24 cycles a second.": "저장한 맵은 eudplib로 빌드되며 리마스터가 필요합니다. 모든 트리거가 매 프레임 실행되므로 타이머는 초당 약 24회로 셉니다.",
  "The script": "스크립트",
  "The script appears here. Edit it before building if you like.": "스크립트가 여기에 나타납니다. 빌드하기 전에 고쳐도 됩니다.",
  "The script has {n, plural, one {# error} other {# errors}}; asking for a repair ({round} of {rounds})…": "스크립트에 오류가 {n, plural, other {#개}} 있습니다. 수정을 요청하는 중 ({round}/{rounds})…",
  "The script still has errors. Fix them here or in TrigScript, then Build.": "스크립트에 아직 오류가 있습니다. 여기나 TrigScript에서 고친 다음 빌드하세요.",
  "The server answered in a form this plugin does not understand: {message}": "서버가 이 플러그인이 이해하지 못하는 형식으로 응답했습니다: {message}",
  "The server does not allow that model: {message}": "서버가 그 모델을 허용하지 않습니다: {message}",
  "The server does not take shared maps from this page.": "서버가 이 페이지에서 오는 공유 맵을 받지 않습니다.",
  "The server is busy.": "서버가 바쁩니다.",
  "The server refused: {message}": "서버가 거부했습니다: {message}",
  "The server rejected the request: {message}": "서버가 요청을 거부했습니다: {message}",
  "The server restarted, which ends every shared map.": "서버가 다시 시작되어 모든 공유 맵이 끝났습니다.",
  "The session has ended: {message} Sign in again from the Account menu.": "세션이 끝났습니다: {message} 계정 메뉴에서 다시 로그인하세요.",
  "The shared map and this editor no longer agree on what was changed. The map is still open here; save it, or join again.": "공유 맵과 이 에디터의 변경 내용이 더 이상 일치하지 않습니다. 맵은 여기에 그대로 열려 있으니 저장하거나 다시 참여하세요.",
  "The shared map closed after nobody used it for a while.": "한동안 아무도 쓰지 않아 공유 맵이 닫혔습니다.",
  "The shared map could not be opened again ({error}). The map is still open here; save it, or join again.": "공유 맵을 다시 열지 못했습니다 ({error}). 맵은 여기에 그대로 열려 있으니 저장하거나 다시 참여하세요.",
  "The shared map could not be opened.": "공유 맵을 열지 못했습니다.",
  "The shared map ended after going its time without an edit. The map and its revisions stay in the owner's My Maps.": "정해진 기간 동안 편집이 없어 공유 맵이 끝났습니다. 맵과 버전은 소유자의 내 맵에 남습니다.",
  "The shared map ended while you were away. The map is still open here; save it, or join again.": "자리를 비운 사이 공유 맵이 끝났습니다. 맵은 여기에 그대로 열려 있으니 저장하거나 다시 참여하세요.",
  "The shared map ended.": "공유 맵이 끝났습니다.",
  "The shared map was closed in this editor.": "이 에디터에서 공유 맵을 닫았습니다.",
  "The shared map: anyone who sees it can join and edit": "공유 맵: 보는 사람 누구나 참여해서 편집할 수 있음",
  "There are no triggers to explain.": "설명할 트리거가 없습니다.",
  "These systems belong to the map the scenario was built on; bring it to the front first.": "이 시스템들은 시나리오를 빌드한 맵의 것입니다. 먼저 그 맵을 앞으로 가져오세요.",
  "Thinking": "생각하는 중",
  "This feature is turned off on the server for now.": "이 기능은 지금 서버에서 꺼져 있습니다.",
  "This server has no pictures for shared maps yet.": "이 서버는 아직 공유 맵 그림을 지원하지 않습니다.",
  "This server has no shared map editing.": "이 서버는 공유 맵 편집을 지원하지 않습니다.",
  "This server keeps no maps.": "이 서버는 맵을 보관하지 않습니다.",
  "This server offers no sign-in.": "이 서버는 로그인을 제공하지 않습니다.",
  "Thorough — the highest setting; slower and dearer": "꼼꼼하게 — 가장 높은 설정, 더 느리고 비쌈",
  "Thought": "생각함",
  "Tileset": "타일셋",
  "Tone, length, language — or leave it to the facts. (\"short and grim\", \"in German\", \"mention the gold expansion\")": "어조, 길이, 언어 — 비워 두면 맵의 정보로 씁니다. (\"짧고 음울하게\", \"독일어로\", \"골드 멀티를 언급\")",
  "Too many requests for now.": "지금은 요청이 너무 많습니다.",
  "Top up or wait": "충전하거나 기다리기",
  "Top up…": "충전…",
  "Transcript copied.": "대화 내용을 복사했습니다.",
  "Translate to…": "번역…",
  "Translate, fix or retone the strings": "문자열을 번역하거나 고치거나 어조를 바꿉니다",
  "Trial started: {amount} to spend.": "체험을 시작했습니다. {amount}까지 쓸 수 있습니다.",
  "Triggers": "트리거",
  "Triggers ({n})": "트리거 ({n})",
  "Triggers only, and no hyper triggers: the trigger list runs about every two seconds, and no timer is finer than that.": "트리거만 쓰고 하이퍼 트리거는 없습니다. 트리거 목록은 약 2초마다 실행되며, 이보다 정밀한 타이머는 없습니다.",
  "Triggers only. The design has hyper triggers, so timers are counted at about 12 cycles a second.": "트리거만 씁니다. 설계에 하이퍼 트리거가 있으므로 타이머는 초당 약 12회로 셉니다.",
  "Try again": "다시 시도",
  "Try again in a moment.": "잠시 후 다시 시도하세요.",
  "Try again in {n, plural, one {# minute} other {# minutes}}.": "{n, plural, other {#분}} 후 다시 시도하세요.",
  "Try again in {n, plural, one {# second} other {# seconds}}.": "{n, plural, other {#초}} 후 다시 시도하세요.",
  "Twilight": "트와일라잇",
  "Type a name for the others to see.": "다른 사람에게 보일 이름을 입력하세요.",
  "Type-check the script ({n, plural, one {# line} other {# lines}})": "스크립트 타입 검사 ({n}줄)",
  "UMS readability": "UMS 가독성",
  "Undo the edits this turn made, newest first": "이 차례에 한 편집을 최신 것부터 실행 취소합니다",
  "Unit Properties": "유닛 속성",
  "Unit Properties Slots": "유닛 속성 슬롯",
  "Unit Settings": "유닛 설정",
  "Unit settings for {unit}: {fields}": "{unit} 유닛 설정: {fields}",
  "Until I end it": "내가 끝낼 때까지",
  "Until everyone leaves": "모두 나갈 때까지",
  "Until you end it": "직접 끝낼 때까지",
  "Upgrade Settings": "업그레이드 설정",
  "Upgrade settings for {upgrade}: {fields}": "{upgrade} 업그레이드 설정: {fields}",
  "Uploading…": "올리는 중…",
  "Use the AI features": "AI 기능 사용",
  "Use the AI features (Tools ▸ AI, the assistant, the AI buttons in the editor's dialogs)": "AI 기능 사용 (도구 ▸ AI, 어시스턴트, 에디터 대화 상자의 AI 버튼)",
  "Use this": "이것 사용",
  "Used by": "사용처",
  "Waiting for the model": "모델을 기다리는 중",
  "Waiting for the server…": "서버를 기다리는 중…",
  "Waiting for {provider}…": "{provider} 로그인을 기다리는 중…",
  "Walk through what these triggers do in play": "게임에서 이 트리거들이 하는 일을 차례로 설명합니다",
  "What": "내용",
  "What changed, or what this version is for (optional)": "무엇이 바뀌었는지, 또는 이 버전의 용도 (선택)",
  "What kind of map? Say how many players, the feel of the terrain, where the bases go, anything the layout should have.": "어떤 맵인가요? 플레이어 수, 지형의 느낌, 기지 위치 등 배치에 들어가야 할 것을 적으세요.",
  "What kind of scenario? A genre and a sentence of story is enough: \"a madness map\", \"an RPG about a lost marine\", \"a four-player tower defense with two lanes\".": "어떤 시나리오인가요? 장르와 이야기 한 문장이면 충분합니다: \"매드니스 맵\", \"길 잃은 마린의 RPG\", \"두 갈래 길이 있는 4인용 타워 디펜스\".",
  "What should change in the design? (\"make it two players\", \"add a boss\", \"less income\")": "설계에서 무엇을 바꿀까요? (\"2인용으로\", \"보스 추가\", \"수입 줄이기\")",
  "What should change? (\"more room around the naturals\", \"swap the lake for a plateau\")": "무엇을 바꿀까요? (\"앞마당 주변을 더 넓게\", \"호수를 고지대로\")",
  "What should happen? (\"each player gets 10 marines at their start every 30 seconds until minute 5\", \"victory when a player has 50 kills\", \"a countdown that ends the game in a draw\")": "무슨 일이 일어나야 하나요? (\"5분까지 30초마다 각 플레이어의 시작 위치에 마린 10기\", \"50킬을 한 플레이어가 승리\", \"무승부로 게임을 끝내는 카운트다운\")",
  "What should this area become? (\"a lake with a bridge\", \"a plateau with one ramp to the south\", \"a forest with a path through it\")": "이 영역을 무엇으로 만들까요? (\"다리가 있는 호수\", \"남쪽으로 경사로가 하나 있는 고지대\", \"가운데로 길이 난 숲\")",
  "What the triggers should do": "트리거가 할 일",
  "What this panel has cost · what the session has cost": "이 패널에서 든 비용 · 세션 전체에서 든 비용",
  "What this session has cost so far": "이번 세션에서 지금까지 든 비용",
  "What to change first": "먼저 바꿀 것",
  "What to do with the strings.": "문자열로 무엇을 할지 적으세요.",
  "What to look at": "볼 것",
  "What to look at — or leave empty for a general review.": "무엇을 볼지 적거나, 비워 두면 전반적으로 검토합니다.",
  "What to make": "만들 것",
  "What to make of it": "만들 것",
  "What to make: {excerpt} · {w}×{h} {tileset} · {n, plural, one {# player} other {# players}}": "만들 것: {excerpt} · {w}×{h} {tileset} · 플레이어 {n, plural, other {#명}}",
  "When": "날짜",
  "Which": "대상",
  "Who is speaking, what is at stake, how long — or leave it to the triggers and the map. (\"a terse Terran commander\", \"three lines\", \"in Spanish\")": "누가 말하는지, 무엇이 걸려 있는지, 얼마나 길게 — 비워 두면 트리거와 맵을 보고 씁니다. (\"말수 적은 테란 지휘관\", \"세 줄\", \"스페인어로\")",
  "Working on the map": "맵 작업 중",
  "Working…": "작업 중…",
  "Write": "작성",
  "Write Briefing": "브리핑 작성",
  "Write Briefing…": "브리핑 작성…",
  "Write Triggers": "트리거 작성",
  "Write Triggers…": "트리거 작성…",
  "Write a trigger script from a description": "설명으로 트리거 스크립트를 씁니다",
  "Write briefing…": "브리핑 쓰기…",
  "Write into the map": "맵에 적기",
  "Write objectives and narration with the AI": "AI와 함께 목표와 내레이션을 씁니다",
  "Write triggers…": "트리거 쓰기…",
  "Writing": "쓰는 중",
  "Writing the answer… {size} characters": "답을 쓰는 중… {size}자",
  "Writing the answer… {size} characters · {last}": "답을 쓰는 중… {size}자 · {last}",
  "Writing…": "작성하는 중…",
  "Written into Scenario ▸ Map Properties. It is not an undo step; write the old one back the same way if you change your mind.": "시나리오 ▸ 맵 속성에 적었습니다. 실행 취소 단계가 아니므로, 마음이 바뀌면 같은 방법으로 이전 것을 다시 적으세요.",
  "Written: {objectives, plural, one {# objective} other {# objectives}} and {messages, plural, one {# message} other {# messages}} in one briefing trigger for all players. Triggers ▸ Mission Briefing shows it.": "모든 플레이어를 위한 브리핑 트리거 하나에 목표 {objectives, plural, other {#개와}} 메시지 {messages, plural, other {#개를}} 적었습니다. 트리거 ▸ 임무 브리핑에서 볼 수 있습니다.",
  "Wrote {n, plural, one {# string} other {# strings}} in place. Not an undo step; Scenario ▸ String Editor shows them.": "문자열 {n, plural, other {#개를}} 제자리에 적었습니다. 실행 취소 단계가 아닙니다. 시나리오 ▸ 문자열 편집기에서 볼 수 있습니다.",
  "You are editing a shared map with others.": "다른 사람들과 공유 맵을 편집하고 있습니다.",
  "You are editing “{name}” with others.": "다른 사람들과 함께 “{name}” 맵을 편집하고 있습니다.",
  "You are in a shared map already; joining this one leaves it.": "이미 공유 맵에 있습니다. 이 맵에 참여하면 지금 맵에서 나갑니다.",
  "You are not sharing any maps.": "공유 중인 맵이 없습니다.",
  "You were away too long to catch up, so the shared map opened again in a new tab. The map as you had it is still open in its own tab, with {n, plural, one {# change} other {# changes}} the others never got.": "너무 오래 연결이 끊겨 따라잡을 수 없어서 공유 맵을 새 탭에 다시 열었습니다. 이전 맵은 다른 사람이 받지 못한 변경 {n}개와 함께 자기 탭에 그대로 열려 있습니다.",
  "You were away too long to catch up, so the shared map opened again in a new tab. The map as you had it is still open in its own tab.": "너무 오래 연결이 끊겨 따라잡을 수 없어서 공유 맵을 새 탭에 다시 열었습니다. 이전 맵은 자기 탭에 그대로 열려 있습니다.",
  "You were removed from the shared map.": "공유 맵에서 제거되었습니다.",
  "You: {text}": "나: {text}",
  "Your name": "내 이름",
  "Your shared maps": "공유 중인 맵",
  "a madness map": "매드니스 맵",
  "a tower defense": "타워 디펜스",
  "account\u0004Balance": "잔액",
  "after {n} rounds of tool calls; Tools ▸ AI ▸ Options… sets the limit": "도구 호출 {n}라운드 후 멈춤. 한도는 도구 ▸ AI ▸ 옵션…에서 정합니다",
  "allied": "동맹",
  "allied victory": "동맹 승리",
  "an RPG": "RPG",
  "area": "영역",
  "at the {ceiling} ceiling for one message ({spent} spent); Tools ▸ AI ▸ Options… sets it": "메시지 하나의 한도 {ceiling}에 도달해 멈춤 ({spent} 사용). 한도는 도구 ▸ AI ▸ 옵션…에서 정합니다",
  "at {x},{y}": "({x},{y})",
  "built by the toolkit": "툴킷이 만듦",
  "by name": "이름별",
  "by owner": "소유자별",
  "by owner and name": "소유자와 이름별",
  "by {group}": "{group}별",
  "changed": "변경됨",
  "clean": "문제 없음",
  "connection lost": "연결 끊김",
  "connection lost, may come back": "연결 끊김, 돌아올 수 있음",
  "east": "동쪽",
  "failed": "실패",
  "for Player {player}": "(플레이어 {player})",
  "from #{n}": "#{n}부터",
  "gives {credit} of credit to start": "시작 크레딧 {credit}",
  "gives {credit} of credit to start and {weekly} a week, refilled every Monday": "시작 크레딧 {credit} 및 매주 월요일에 다시 채워지는 주간 {weekly}",
  "gives {weekly} a week, refilled every Monday": "매주 월요일에 다시 채워지는 주간 {weekly}",
  "heights": "높이",
  "in {dialog}": "{dialog} 사용 중",
  "in {rect}": "{rect} 안",
  "info": "정보",
  "it speaks protocol {theirs}, this plugin speaks {ours}.": "서버의 프로토콜은 {theirs}, 이 플러그인의 프로토콜은 {ours}입니다.",
  "just now": "방금",
  "keeps your balance across browsers": "브라우저가 바뀌어도 유지되는 잔액",
  "line to the {direction}": "자원 줄은 {direction}",
  "line {line}:{column} — {message}": "{line}:{column}행 — {message}",
  "map": "맵",
  "name": "이름",
  "named \"{name}\"": "이름 \"{name}\"",
  "no map is open.": "열린 맵이 없습니다.",
  "no plan came back": "계획이 돌아오지 않았습니다",
  "no problems": "문제 없음",
  "no server address is set.": "서버 주소가 설정되지 않았습니다.",
  "no symmetry": "대칭 없음",
  "no: {reason}": "아니요: {reason}",
  "north": "북쪽",
  "north-east": "북동쪽",
  "north-west": "북서쪽",
  "not a kind the toolkit has": "툴킷에 없는 종류",
  "not called": "호출되지 않음",
  "not run": "실행 안 함",
  "not run: stopped": "실행 안 함: 중지됨",
  "nothing": "없음",
  "nothing changed": "바뀐 것 없음",
  "nothing left out": "빠진 것 없음",
  "nothing placed: {reason}": "배치된 것 없음: {reason}",
  "nothing to add": "추가할 것 없음",
  "nothing was placed": "배치된 것이 없습니다",
  "nothing wrong": "문제 없음",
  "over {list}": "덮은 것: {list}",
  "owner {n}": "소유자 {n}",
  "picture": "그림",
  "problem": "문제",
  "properties": "속성",
  "refills {day}": "{day} 충전",
  "revision #{n}": "버전 #{n}",
  "round {n}": "{n}번째 라운드",
  "scmjs.dev Account": "scmjs.dev 계정",
  "scmjs.dev Account…": "scmjs.dev 계정…",
  "scmjs.dev could not be reached: {message} Check your connection and try again.": "scmjs.dev에 연결할 수 없습니다: {message} 연결을 확인하고 다시 시도하세요.",
  "scmjs.dev keeps your provider id, display name, a ledger of what your calls cost, and the maps you store — nothing else, never a prompt or a card. Delete all of it from the account page at {site}.": "scmjs.dev는 로그인 제공자 ID, 표시 이름, 호출 비용 사용 내역, 보관한 맵만 저장합니다. 프롬프트나 카드 정보는 절대 저장하지 않습니다. {site}의 계정 페이지에서 전부 삭제할 수 있습니다.",
  "scmjs.dev plans the layout; this takes a few minutes": "scmjs.dev가 배치를 계획합니다. 몇 분 걸립니다",
  "scmjs.dev trial": "scmjs.dev 체험",
  "scmjs.dev trial · {balance}": "scmjs.dev 체험 · {balance}",
  "screenshot": "스크린샷",
  "shared the map": "맵을 공유함",
  "shared vision": "시야 공유",
  "south": "남쪽",
  "south-east": "남동쪽",
  "south-west": "남서쪽",
  "start locations for {n, plural, one {player {players}} other {players {players}}} were placed by the editor; check where": "플레이어 {players}의 시작 위치는 에디터가 놓았습니다. 위치를 확인하세요",
  "terrain {id}": "지형 {id}",
  "the Sound Editor": "사운드 편집기",
  "the String Editor": "문자열 편집기",
  "the TrigScript plugin is off": "TrigScript 플러그인이 꺼져 있습니다",
  "the Trigger Editor": "트리거 편집기",
  "the answer was cut off at the output limit; Continue picks it up": "출력 한도에서 답이 끊겼습니다. 계속을 누르면 이어서 씁니다",
  "the area {rect}": "영역 {rect}",
  "the browser blocked the sign-in window; allow popups for this site and try again.": "브라우저가 로그인 창을 막았습니다. 이 사이트의 팝업을 허용하고 다시 시도하세요.",
  "the build failed": "빌드에 실패했습니다",
  "the design's systems need {counters} death counters and the map has {free} free ({by}). Remove or merge systems in the design — several obstacle stretches on one beat, one spawn with {p} instead of one per player — and build again": "설계의 시스템에 데스 카운터 {counters}개가 필요한데 맵에는 {free}개만 비어 있습니다 ({by}). 설계에서 시스템을 빼거나 합친 뒤(장애물 구간 여럿을 한 박자에, 플레이어마다 하나씩이 아닌 {p|로} 스폰 하나) 다시 빌드하세요",
  "the location list": "로케이션 목록",
  "the map could not be packed.": "맵을 묶지 못했습니다.",
  "the map could not be rendered (tileset graphics missing?)": "맵을 그릴 수 없습니다 (타일셋 그래픽이 없나요?)",
  "the map in front changed while the assistant was working, so the turn stopped; ask again on the map it should work on": "어시스턴트가 작업하는 동안 앞에 있는 맵이 바뀌어서 이번 차례를 멈췄습니다. 작업할 맵에서 다시 요청하세요",
  "the model did not answer": "모델이 응답하지 않았습니다",
  "the model did not answer the repair": "모델이 수정 요청에 응답하지 않았습니다",
  "the newest save": "최신 저장본",
  "the plan could not be rendered": "계획을 그릴 수 없습니다",
  "the script has {n, plural, one {# error} other {# errors}} after {rounds} repairs; open TrigScript to fix it": "{rounds}번 수정한 뒤에도 스크립트에 오류가 {n, plural, other {#개}} 있습니다. TrigScript를 열어 고치세요",
  "the script still uses program() after {rounds} repairs, which this map (for every version of StarCraft) cannot have; change the design to Remastered, or open TrigScript to rewrite it": "{rounds}번 수정한 뒤에도 스크립트가 program()을 씁니다. 이 맵(모든 버전의 스타크래프트용)에는 쓸 수 없습니다. 설계를 리마스터용으로 바꾸거나 TrigScript를 열어 다시 작성하세요",
  "the shared map is not open.": "공유 맵이 열려 있지 않습니다.",
  "the sign-in did not finish in time.": "로그인이 제시간에 끝나지 않았습니다.",
  "the stream ended without a result.": "스트림이 결과 없이 끝났습니다.",
  "the stream had no body.": "스트림에 본문이 없습니다.",
  "the toolkit has no kind \"{kind}\"": "툴킷에 \"{kind}\" 종류가 없습니다",
  "this server has no pictures for links yet.": "이 서버는 아직 링크 그림을 지원하지 않습니다.",
  "this server offers no sign-in.": "이 서버는 로그인을 제공하지 않습니다.",
  "to #{n}": "#{n}까지",
  "untitled map": "제목 없는 맵",
  "warning": "경고",
  "west": "서쪽",
  "written as a trigger script": "트리거 스크립트로 작성",
  "yes, {n, plural, one {# tile} other {# tiles}} reached": "예, 타일 {n}개에 도달",
  "yesterday": "어제",
  "you": "나",
  "{balance} ({weekly} weekly + {credit} credit)": "{balance} (주간 {weekly} + 크레딧 {credit})",
  "{balance} left": "{balance} 남음",
  "{bases, plural, one {# base} other {# bases}}, {expansions, plural, one {# expansion} other {# expansions}}": "기지 {bases}개, 확장 {expansions}개",
  "{bases, plural, one {# base} other {# bases}}, {ramps, plural, one {# ramp} other {# ramps}}, {rules, plural, one {# decoration rule} other {# decoration rules}}, {units, plural, one {# unit} other {# units}}, {locations, plural, one {# location} other {# locations}}.": "기지 {bases, plural, other {#개}}, 경사로 {ramps, plural, other {#개}}, 장식 규칙 {rules, plural, other {#개}}, 유닛 {units, plural, other {#개}}, 로케이션 {locations, plural, other {#개}}.",
  "{cost} · {time} · {input} in / {output} out": "{cost} · {time} · 입력 {input} / 출력 {output}",
  "{counters} of {free} free death counters, {switches, plural, one {# switch} other {# switches}}": "빈 데스 카운터 {free}개 중 {counters}개, 스위치 {switches}개",
  "{count} of {total}": "{total}개 중 {count}개",
  "{count} of {total}, more follow": "{total}개 중 {count}개, 더 있음",
  "{day}, to {amount}": "{day}, {amount}까지",
  "{file} line {line}:{column} — {message}": "{file} {line}:{column}행 — {message}",
  "{fixed} fixed": "{fixed}개 고침",
  "{genre}: {name} — {systems, plural, one {# system} other {# systems}}, {locations, plural, one {# location} other {# locations}}, {humans, plural, one {# human player} other {# human players}}{target, select, remastered {, for Remastered} other {}}": "{genre}: {name} — 시스템 {systems, plural, other {#개}}, 로케이션 {locations, plural, other {#개}}, 사람 플레이어 {humans, plural, other {#명}}{target, select, remastered {, 리마스터용} other {}}",
  "{groups, plural, one {# group} other {# groups}} of {n, plural, one {# unit} other {# units}}": "유닛 {n}개, 묶음 {groups}개",
  "{here} here · {session} session": "여기 {here} · 세션 {session}",
  "{kind} (player {player}) at {x},{y}, minerals to the {direction}, {minerals} patches, {geysers, plural, one {# geyser} other {# geysers}}": "{kind} (플레이어 {player}) {x},{y}, 미네랄 방향 {direction}, 미네랄 {minerals}덩이, 가스 {geysers, plural, other {#개}}",
  "{kind} at {x},{y}, minerals to the {direction}, {minerals} patches, {geysers, plural, one {# geyser} other {# geysers}}": "{kind} {x},{y}, 미네랄 방향 {direction}, 미네랄 {minerals}덩이, 가스 {geysers, plural, other {#개}}",
  "{label}… {s} s": "{label}… {s}초",
  "{list} and {n} more": "{list} 외 {n}개",
  "{list} {filters}": "{list} ({filters})",
  "{maps, plural, one {# map} other {# maps}}, {revisions, plural, one {# revision} other {# revisions}}. Account ▸ My Maps… lists them; Account ▸ Save to scmjs.dev… adds one.": "맵 {maps, plural, other {#개}}, 버전 {revisions, plural, other {#개}}. 계정 ▸ 내 맵…에서 목록을 보고, 계정 ▸ scmjs.dev에 저장…으로 추가합니다.",
  "{message} Sign in to scmjs.dev to keep a balance and get the sign-in credit.": "{message} scmjs.dev에 로그인하면 잔액을 유지하고 로그인 크레딧을 받을 수 있습니다.",
  "{message} The map is still open here; save it, or join again.": "{message} 맵은 여기에 그대로 열려 있으니 저장하거나 다시 참여하세요.",
  "{minerals, plural, one {# patch} other {# patches}}, {geysers, plural, one {# geyser} other {# geysers}} to the {direction}": "{direction}에 미네랄 {minerals}덩이, 가스 간헐천 {geysers}개",
  "{n, plural, one {# base} other {# bases}} listed (mirrored on apply)": "기지 {n, plural, other {#개}} (적용할 때 대칭됨)",
  "{n, plural, one {# bridge} other {# bridges}}": "다리 {n}개",
  "{n, plural, one {# diamond painted} other {# diamonds painted}}": "다이아몬드 {n}개 칠함",
  "{n, plural, one {# doodad} other {# doodads}}": "장식물 {n}개",
  "{n, plural, one {# edit} other {# edits}}": "{n, plural, other {편집 #개}}",
  "{n, plural, one {# error} other {# errors}}:": "오류 {n, plural, other {#개}}:",
  "{n, plural, one {# finding} other {# findings}}": "문제 {n}개",
  "{n, plural, one {# force} other {# forces}} changed": "세력 {n}개 변경",
  "{n, plural, one {# item} other {# items}}": "항목 {n}개",
  "{n, plural, one {# line} other {# lines}}": "{n, plural, other {#줄}}",
  "{n, plural, one {# location} other {# locations}}": "로케이션 {n}개",
  "{n, plural, one {# location} other {# locations}} the plan did not place: {names}. The systems that need them wait; draw the locations (Layers ▸ Locations), then build the waiting systems below.": "계획이 배치하지 않은 로케이션 {n, plural, other {#개}}: {names}. 이 로케이션이 필요한 시스템은 기다립니다. 로케이션을 그린 다음(레이어 ▸ 로케이션) 아래에서 기다리는 시스템을 빌드하세요.",
  "{n, plural, one {# month ago} other {# months ago}}": "{n, plural, other {#개월 전}}",
  "{n, plural, one {# note} other {# notes}} from the build": "빌드 메모 {n, plural, other {#개}}",
  "{n, plural, one {# person} other {# people}} editing it.": "{n}명이 편집 중입니다.",
  "{n, plural, one {# person} other {# people}} in the map": "맵 안에 {n}명",
  "{n, plural, one {# player} other {# players}} changed": "플레이어 {n}명 변경",
  "{n, plural, one {# problem} other {# problems}}": "문제 {n}개",
  "{n, plural, one {# problem} other {# problems}}, {fixed} fixed": "문제 {n}개, {fixed}개 고침",
  "{n, plural, one {# ramp} other {# ramps}}": "경사로 {n}개",
  "{n, plural, one {# resource} other {# resources}}": "자원 {n}개",
  "{n, plural, one {# settings change} other {# settings changes}} (not undoable)": "{n, plural, other {설정 변경 #개}} (실행 취소 불가)",
  "{n, plural, one {# setting} other {# settings}} written, {humans, plural, one {# human player} other {# human players}}": "설정 {n, plural, other {#개}} 적음, 사람 플레이어 {humans, plural, other {#명}}",
  "{n, plural, one {# setting} other {# settings}} written, {humans, plural, one {# human player} other {# human players}}, {keepers, plural, one {# keeper} other {# keepers}}": "설정 {n, plural, other {#개}} 적음, 사람 플레이어 {humans, plural, other {#명}}, 유지 유닛 {keepers, plural, other {#개}}",
  "{n, plural, one {# site} other {# sites}}": "자리 {n}곳",
  "{n, plural, one {# sprite} other {# sprites}}": "스프라이트 {n}개",
  "{n, plural, one {# start location} other {# start locations}}": "시작 위치 {n}개",
  "{n, plural, one {# step} other {# steps}}": "{n, plural, other {#단계}}",
  "{n, plural, one {# step} other {# steps}} so far · {cost} · waiting for the model": "지금까지 {n, plural, other {#단계}} · {cost} · 모델을 기다리는 중",
  "{n, plural, one {# system waits} other {# systems wait}} for locations the plan did not place: {names}. Draw them, then build.": "시스템 {n, plural, other {#개가}} 계획이 배치하지 않은 로케이션을 기다립니다: {names}. 로케이션을 그린 다음 빌드하세요.",
  "{n, plural, one {# thing} other {# things}} to know": "알아 둘 것 {n, plural, other {#가지}}",
  "{n, plural, one {# thing} other {# things}} to look at": "살펴볼 것 {n, plural, other {#가지}}",
  "{n, plural, one {# tile laid} other {# tiles laid}}": "타일 {n}개 놓음",
  "{n, plural, one {# tile} other {# tiles}}": "타일 {n}개",
  "{n, plural, one {# trigger} other {# triggers}}": "트리거 {n, plural, other {#개}}",
  "{n, plural, one {# trigger} other {# triggers}} added, {total} in all": "트리거 {n}개 추가, 모두 {total}개",
  "{n, plural, one {# trigger} other {# triggers}} from a script: {summary}": "스크립트에서 트리거 {n, plural, other {#개}}: {summary}",
  "{n, plural, one {# unit} other {# units}}": "유닛 {n}개",
  "{n, plural, one {# year ago} other {# years ago}}": "{n, plural, other {#년 전}}",
  "{n, plural, one {Undid # edit.} other {Undid # edits.}}": "{n, plural, other {편집 #개를 실행 취소했습니다.}}",
  "{n, plural, one {Undo it} other {Undo these #}}": "{n, plural, =1 {실행 취소} other {#개 실행 취소}}",
  "{n, plural, one {player {players}} other {players {players}}} (computer) owned nothing, which would defeat them at once and stop their triggers: a {unit} in the top-right corner keeps them in the game": "플레이어 {players}(컴퓨터)에게 아무것도 없어 곧바로 패배하고 트리거가 멈출 뻔했습니다. 오른쪽 위 모서리의 {unit|이} 게임에 남아 있게 합니다",
  "{n, plural, one {player {players}} other {players {players}}}: race set to {race} instead of User Selectable — the game drops a User Selectable player's placed buildings and gives a melee start instead": "플레이어 {players}: 종족을 사용자 선택 대신 {race|으로} 설정했습니다 — 게임은 사용자 선택 플레이어가 배치한 건물을 없애고 밀리 시작을 줍니다",
  "{n, plural, one {waits for location {names}} other {waits for locations {names}}}": "로케이션 {names} 기다리는 중",
  "{name} (you)": "{name} (나)",
  "{name} in the chat": "{name}의 채팅",
  "{name} joined the shared map": "{name|이} 공유 맵에 들어왔습니다",
  "{name} left the shared map.": "{name|이} 공유 맵에서 나갔습니다.",
  "{name} lost the connection to the shared map.": "{name}의 공유 맵 연결이 끊겼습니다.",
  "{name} was removed from the shared map.": "{name|이} 공유 맵에서 제거되었습니다.",
  "{name} · no balance is kept": "{name} · 잔액을 따로 관리하지 않음",
  "{name} · {balance} left": "{name} · {balance} 남음",
  "{name} — new revision #{n}": "{name} — 새 버전 #{n}",
  "{name}: left out — on a Remastered map every trigger already runs each frame": "{name}: 제외됨 — 리마스터 맵에서는 모든 트리거가 이미 매 프레임 실행됩니다",
  "{n} days ago": "{n}일 전",
  "{n} failed": "{n}개 실패",
  "{n} h ago": "{n}시간 전",
  "{n} min ago": "{n}분 전",
  "{n} ms": "{n}ms",
  "{n} not run": "{n}개 실행 안 됨",
  "{n} of {limit} shared maps.": "공유 맵 {limit}개 중 {n}개.",
  "{n} of {total, plural, one {# string} other {# strings}} would change. Untick any to keep, then Apply.": "문자열 {total, plural, other {#개}} 중 {n}개가 바뀝니다. 유지할 것은 체크를 해제한 다음 적용하세요.",
  "{n} placed on the map": "맵에 {n}개 배치",
  "{n} s": "{n}초",
  "{n} waiting": "{n}개 대기",
  "{outcome} Every edit is an undo step; the settings and triggers are transactions outside undo, as in StarEdit.": "{outcome} 모든 편집은 실행 취소 단계입니다. 설정과 트리거는 StarEdit처럼 실행 취소 밖의 작업입니다.",
  "{placed} placed": "{placed}개 배치",
  "{placed} placed, {refused} refused": "{placed}개 배치, {refused}개 거부",
  "{players, plural, one {# player} other {# players}}": "플레이어 {players}명",
  "{players, plural, one {# player} other {# players}} ({humans} human)": "플레이어 {players}명 (사람 {humans}명)",
  "{price} for {credit} of credit": "{price}에 크레딧 {credit}",
  "{px} px per tile": "타일당 {px}px",
  "{ramps, plural, one {# ramp} other {# ramps}}, {rules, plural, one {# decoration rule} other {# decoration rules}}, {units, plural, one {# unit} other {# units}}, {locations, plural, one {# location} other {# locations}}.": "경사로 {ramps, plural, other {#개}}, 장식 규칙 {rules, plural, other {#개}}, 유닛 {units, plural, other {#개}}, 로케이션 {locations, plural, other {#개}}.",
  "{revisions, plural, one {# revision} other {# revisions}} · {size}": "버전 {revisions}개 · {size}",
  "{revisions, plural, one {# revision} other {# revisions}} · {size} · {links, plural, one {# link} other {# links}}": "버전 {revisions}개 · {size} · 링크 {links}개",
  "{role} · no balance is kept": "{role} · 잔액을 따로 관리하지 않음",
  "{session} session": "세션 {session}",
  "{shared} · you are in it": "{shared} · 참여 중",
  "{size} · created {date}": "{size} · {date} 만듦",
  "{spent} of {ceiling}": "{spent} / {ceiling}",
  "{s} s": "{s}초",
  "{used} MB of {cap} MB of map storage used": "맵 저장 공간 {cap} MB 중 {used} MB 사용",
  "{used} of {cap} used": "{cap} 중 {used} 사용",
  "{used} of {cap} used.": "{cap} 중 {used} 사용.",
  "{what} copied.": "{what} 복사됨.",
  "{which} · opened {n}×": "{which} · {n}회 열림",
  "{w} × {h} tiles, {cell, plural, one {# tile} other {# tiles}} per cell. The model is shown the area with {margin} tiles of margin so the edges join.": "{w} × {h} 타일, 칸당 {cell, plural, other {#타일}}. 가장자리가 이어지도록 모델에게 영역 둘레 {margin}타일까지 보여 줍니다.",
  "“{name}” · {n} of {max} people editing now.": "“{name}” · 지금 {max}명 중 {n}명 편집 중.",
  "“{name}”, shared by {owner} · {n} of {max} people editing now.": "“{name}”, 공유한 사람 {owner} · 지금 {max}명 중 {n}명 편집 중.",
};
